# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import podlife.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugfield', models.SlugField(editable=False, max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('audio_file', models.FileField(null=True, upload_to=podlife.models.file_path)),
                ('file_type', models.CharField(choices=[('WAV', '.wav'), ('MP3', '.mp3')], default='WAV', max_length=3)),
                ('file_path', models.CharField(editable=False, max_length=220, null=True)),
                ('views', models.IntegerField(default=0, editable=False)),
                ('num_comments', models.IntegerField(default=0, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='podcasts',
            name='topic',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='podlife.Topics'),
        ),
        migrations.AddField(
            model_name='comments',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podlife.Podcasts'),
        ),
    ]
