# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podlife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicsubscription',
            name='pod',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pod', to='podlife.Topic'),
        ),
        migrations.AlterField(
            model_name='topicsubscription',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='topicuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
