# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podlife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcasts',
            name='num_downvotes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='num_favorites',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='num_upvotes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='topics',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='num_podcasts',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
