# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podlife', '0002_auto_20171116_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='num_subscribers',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
