# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podlife', '0002_auto_20171209_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='num_favorites',
        ),
    ]
