# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podlife', '0003_topics_num_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcasts',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topics',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
