# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podlife', '0004_auto_20171117_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcasts',
            old_name='file_path',
            new_name='audio_file_path',
        ),
    ]
