# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podlife', '0005_auto_20171117_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcasts',
            old_name='audio_file_path',
            new_name='file_path',
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='audio_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
